### PR TITLE
Updated for Map Pool and other minor updates

### PR DESCRIPTION
**Pull request by Durgulach**
Update for map pool and change of outdated language.

Map Pool section added
Map Selection section added
added Tournament Draft mode as the required mode for in-game draft tool
added referee status to casters
Changed scheduling from "Every night of the week" to reflect new format.

### CODE REVIEW

**Review by synthparadox — COMMENTED** [review]
Typo at last line of Competitive Map Pool: battlefeilds

**Review by Hammwich — CHANGES_REQUESTED** [review]
Map selection section should be a list of rules, this paragraph style does not in my opinion highlight the most important message, 

1) A map may be played 1 time per series
2) The first map of the series will be picked by the Visiting Team
3) The map chosen must be from the map pool below: 
   [List Map Pool] 

It's nice to try and add some flavor to the rules, but in my opinion it dilutes their purpose and leaves room for confusion or worse, people simply ignoring them.  

In addition I had created a pull request prior to the creation of this one or so I thought, is their a way to avoid duplicating work like this?

**Comment by Durgulach** [comment]
We posted them like a minute apart lol.  Generally I agree that flavor can be distracting but was trying to err away from legalese

**Comment by Hammwich** [comment]
Yeah I like the compromise Jova came up with, I think the fun lead in is good to have, just want to make sure when people are looking for the rules they are clear and easy to find.

**Pull request merged**
